version: '3.8'

services:
  postgres:
    image: "postgres:13"
    container_name: postgres
    volumes:
      - feiranamao-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - net_feiranamao

#docker run -p 8090:80 -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' --name pgAdmin4 --network 2020-feiranamao_net_feiranamao -d dpage/pgadmin4
  #server: container_name do postgres 

#apagando dados do banco modelo antigo:
#docker volume rm 2020-feiranamao_feiranamao-data

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - 8380:8380
  #   depends_on:
  #     - postgres
  #   networks:
  #     - net_feiranamao

  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  #   networks:
  #     - net_feiranamao

#CRIA O VOLUME QUE É USADO PARA O BANCO
volumes:
  feiranamao-data: #DEFAULT, WINDOWS COM WSL: \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\

networks:
  net_feiranamao:
    driver: bridge